<a href="https://colab.research.google.com/github/aylaismayilzada6/Data-and-Information-Engineering-ENCE24-/blob/main/Homework3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandasql
import pandas as pd
import pandasql as psql
Customer=pd.read_excel("https://github.com/ogut77/BA/blob/main/Customer.xlsx?raw=true")
Employee=pd.read_excel("https://github.com/ogut77/BA/blob/main/Employee.xlsx?raw=true")
Employee_1=pd.read_excel("https://github.com/ogut77/BA/blob/main/Employee.xlsx?raw=true")
Product=pd.read_excel("https://github.com/ogut77/BA/blob/main/Product.xlsx?raw=true")
OrdLine=pd.read_excel("https://github.com/ogut77/BA/blob/main/OrdLine.xlsx?raw=true")
OrderTbl=pd.read_excel("https://github.com/ogut77/BA/blob/main/OrderTbl.xlsx?raw=true")

Collecting pandasql
  Downloading pandasql-0.7.3.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.1.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.2.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (from pandasql) (2.1.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pandasql) (2026.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy->pandasql) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pandasql) (1.17.0)
Building wheels for collected packages: pandasql
  Building wheel for pandasql (setup.py) ... done
  Created wheel for pandasql: filename=pandasql-0.7.3-py3-none-any.whl size=26867 sha256=890cf21dba8fd62dc168b74e5eccba29e808ae987f36ba760f782b5a2df030db
  Stored in directory: /root/.cache/pip/wheels/b4/d0/8c/a6b366870bf041849cd96e03b71641e082f8d6456269b603b7
Successfully built pandasql
Installing collected packages: pandasql
Successfully installed pandasql-0.7.3

In [2]:
#1-List the order number, order date, customer number and customer name (first and last) of orders
# placed in January 2017 sent to Colorado recipients (OrdState).
txt='''
SELECT OrderTbl.OrdNo, OrderTbl.OrdDate, Customer.CustNo, Customer.CustFirstName, Customer.CustLastName
FROM Customer JOIN OrderTbl ON Customer.CustNo = OrderTbl.CustNo
WHERE OrderTbl.OrdDate >= '2017-01-01' AND  OrderTbl.OrdDate <= '2017-01-31' AND OrderTbl.OrdState = 'CO';


'''
Q1 =  psql.sqldf(txt)
Q1

      OrdNo                     OrdDate    CustNo CustFirstName CustLastName
0  O1116324  2017-01-23 00:00:00.000000  C0954327         Sheri       Gordon
1  O3252629  2017-01-23 00:00:00.000000  C9403348          Mike        Boren
2  O3331222  2017-01-13 00:00:00.000000  C1010398           Jim     Glussman
3  O3377543  2017-01-15 00:00:00.000000  C9128574         Jerry        Wyatt

In [4]:
#2-List the order number, order date, and customer number and customer name (first and last) of orders
# placed before January 23, 2017, where customer address (CusState) is in Colorado ('CO')
txt='''
SELECT OrderTbl.OrdNo, OrderTbl.OrdDate, Customer.CustNo, Customer.CustFirstName, Customer.CustLastName
FROM Customer JOIN OrderTbl ON Customer.CustNo = OrderTbl.CustNo
WHERE  OrdDate<'2017-01-23' and CustState='CO'
'''
Q2 =  psql.sqldf(txt)
Q2

      OrdNo                     OrdDate    CustNo CustFirstName CustLastName
0  O2334661  2017-01-14 00:00:00.000000  C0954327         Sheri       Gordon
1  O3331222  2017-01-13 00:00:00.000000  C1010398           Jim     Glussman
2  O3377543  2017-01-15 00:00:00.000000  C9128574         Jerry        Wyatt
3  O6565656  2017-01-20 00:00:00.000000  C9865874          Mary         Hill

In [7]:
#3-List the order number, order date, customer number and
#customer name (first and last) of orders placed in January 2017 placed by Colorado customers
#(CustState) but sent to Washington recipients (OrdState).
txt='''
SELECT OrderTbl.OrdNo, OrderTbl.OrdDate, Customer.CustNo, Customer.CustFirstName, Customer.CustLastName
FROM Customer JOIN OrderTbl ON Customer.CustNo = OrderTbl.CustNo
WHERE OrderTbl.OrdDate >= '2017-01-01' AND  OrderTbl.OrdDate <= '2017-01-31' AND Customer.CustState = 'CO' AND OrderTbl.OrdState = 'WA';
'''
Q3 =  psql.sqldf(txt)
Q3

      OrdNo                     OrdDate    CustNo CustFirstName CustLastName
0  O2334661  2017-01-14 00:00:00.000000  C0954327         Sheri       Gordon
1  O6565656  2017-01-20 00:00:00.000000  C9865874          Mary         Hill
2  O8979495  2017-01-23 00:00:00.000000  C9865874          Mary         Hill

In [ ]:
#3-List the order number, order date, customer number and
#customer name (first and last) of orders placed in January 2017 placed by Colorado customers
#(CustState) but sent to Washington recipients (OrdState).
txt='''
SELECT OrderTbl.OrdNo, OrderTbl.OrdDate, Customer.CustNo, Customer.CustFirstName, Customer.CustLastName
FROM Customer JOIN OrderTbl ON Customer.CustNo = OrderTbl.CustNo
WHERE OrderTbl.OrdDate >= '2017-01-01' AND  OrderTbl.OrdDate <= '2017-01-31' AND Customer.CustState = 'CO' AND OrderTbl.OrdState = 'WA';
'''
Q3 =  psql.sqldf(txt)
Q3

,CustNo,CustFirstName,CustLastName,CustStreet,CustCity,CustState,CustZip,CustBal,OrdNo,OrdDate,CustNo,EmpNo,OrdName,OrdStreet,OrdCity,OrdState,OrdZip
0,C2388597,Beth,Taylor,2396 Rafter Rd,Seattle,WA,98103-1121,500,O2233457,2017-01-12 00:00:00.000000,C2388597,E9884325,Beth Taylor,2396 Rafter Rd,Seattle,WA,98103-1121
1,C2388597,Beth,Taylor,2396 Rafter Rd,Seattle,WA,98103-1121,500,O4714645,2017-01-11 00:00:00.000000,C2388597,E1329594,Beth Taylor,2396 Rafter Rd,Seattle,WA,98103-1121
2,C3340959,Betty,Wise,4334 153rd NW,Seattle,WA,98178-3311,200,O5511365,2017-01-22 00:00:00.000000,C3340959,E9884325,Betty White,4334 153rd NW,Seattle,WA,98178-3311
3,C3499503,Bob,Mann,1190 Lorraine Cir.,Monroe,WA,98013-1095,0,O7989497,2017-01-16 00:00:00.000000,C3499503,E9345771,Bob Mann,1190 Lorraine Cir.,Monroe,WA,98013-1095
4,C8574932,Wally,Jones,411 Webber Ave.,Seattle,WA,98105-1093,1500,O1455122,2017-01-09 00:00:00.000000,C8574932,E9345771,Wally Jones,411 Webber Ave.,Seattle,WA,98105-1093
5,C9543029,Sharon,Johnson,1223 Meyer Way,Fife,WA,98222-1123,856,O1579999,2017-01-05 00:00:00.000000,C9543029,E8544399,Tom Johnson,1632 Ocean Dr.,Des Moines,WA,98222-1123

In [9]:
#4-List the customer number, name (first and last), and balance of Washington
#customers who have placed  one or more orders in February 2017.
txt='''
SELECT DISTINCT Customer.CustNo, Customer.CustFirstName, Customer.CustLastName, Customer.CustBal
FROM Customer JOIN OrderTbl ON Customer.CustNo = OrderTbl.CustNo
WHERE OrderTbl.OrdDate >= '2017-02-01' AND  OrderTbl.OrdDate <= '2017-02-28' AND Customer.CustState = 'WA';
'''
Q4 =  psql.sqldf(txt)
Q4

     CustNo CustFirstName CustLastName  CustBal
0  C8543321           Ron     Thompson       85
1  C9549302          Todd        Hayes        0
2  C9857432         Homer        Wells      500

In [10]:
#5-List the customer number, name (first and last), and balance of Washington
#customers who have placed  more than 1 order in February 2017.
txt='''
SELECT  Customer.CustNo, Customer.CustFirstName, Customer.CustLastName, Customer.CustBal
FROM Customer JOIN OrderTbl ON Customer.CustNo = OrderTbl.CustNo
WHERE OrderTbl.OrdDate >= '2017-02-01' AND  OrderTbl.OrdDate <= '2017-02-28' AND Customer.CustState = 'WA'
GROUP BY Customer.CustNo, Customer.CustFirstName, Customer.CustLastName, Customer.CustBal
HAVING COUNT(*) > 1;
'''
Q5 =  psql.sqldf(txt)
Q5

     CustNo CustFirstName CustLastName  CustBal
0  C8543321           Ron     Thompson       85

In [12]:
#6-List product related information if product price is lower than average price
txt='''
SELECT ProdNo, ProdName, ProdMfg, ProdQOH, ProdPrice, ProdNextShipDate
FROM Product
WHERE ProdPrice < (SELECT AVG(ProdPrice) FROM Product);
'''
Q6 =  psql.sqldf(txt)
Q6

,ProdNo,ProdName,ProdMfg,ProdQOH,ProdPrice,ProdNextShipDate
0,P1412138,10 Foot Printer Cable,Ethlite,100,12.00,None
1,P1445671,8-Outlet Surge Protector,Intersafe,33,14.99,None
2,P1556678,CVP Ink Jet Color Printer,Connex,8,99.00,2017-01-22 00:00:00.000000
3,P3455443,Color Ink Jet Cartridge,Connex,24,38.00,2017-01-22 00:00:00.000000
4,P6677900,Black Ink Jet Cartridge,Connex,44,25.69,None
5,P9995676,Battery Back-up System,Cybercx,12,89.00,2017-02-01 00:00:00.000000

In [13]:
#7-if product price is lower than average price, find how many times are they ordered?
#List product price as well.
txt='''
SELECT Product.ProdNo, Product.ProdPrice, COUNT(OrdNo) as 'Number of Order'
FROM Product JOIN OrdLine ON Product.ProdNo = OrdLine.ProdNo
WHERE ProdPrice < (SELECT AVG(ProdPrice) FROM Product) GROUP BY Product.ProdNo, Product.ProdPrice;
'''
Q7 =  psql.sqldf(txt)
Q7

     ProdNo  ProdPrice  Number of Order
0  P1412138      12.00                6
1  P1445671      14.99                9
2  P1556678      99.00                7
3  P3455443      38.00                3
4  P6677900      25.69                4
5  P9995676      89.00                4

In [26]:
#8-List the order number and total amount for orders placed each day.

txt='''
SELECT DATE(OrderTbl.OrdDate) AS Date,
       COUNT(DISTINCT OrderTbl.OrdNo)  AS 'Number of Order',
       SUM(Product.ProdPrice * OrdLine.Qty) AS Amount
FROM OrderTbl
JOIN OrdLine
    ON OrderTbl.OrdNo = OrdLine.OrdNo
JOIN Product
    ON OrdLine.ProdNo = Product.ProdNo
GROUP BY DATE(OrderTbl.OrdDate), OrderTbl.OrdNo
ORDER BY DATE(OrderTbl.OrdDate);
'''
Q8 =  psql.sqldf(txt)
Q8

          Date  Number of Order   Amount
0   2017-01-05                1   213.69
1   2017-01-09                1   199.99
2   2017-01-11                1   258.00
3   2017-01-12                1   333.99
4   2017-01-13                1   149.00
5   2017-01-14                1   280.00
6   2017-01-15                1   103.99
7   2017-01-16                1  1466.97
8   2017-01-20                1  1690.00
9   2017-01-22                1   189.68
10  2017-01-23                1    14.99
11  2017-01-23                1   183.99
12  2017-01-23                1   383.98
13  2017-01-23                1   288.99
14  2017-01-23                1   124.69
15  2017-01-23                1   725.99
16  2017-02-10                1   319.00
17  2017-02-11                1   113.99
18  2017-02-11                1  1217.99
19  2017-02-19                1   873.45

In [32]:
#9-What is the total value of product sold by each employee?
#Included internet orders as well
txt='''
SELECT OrderTbl.EmpNo, SUM(Product.ProdPrice * OrdLine.Qty) AS Amount
FROM OrderTbl
JOIN OrdLine ON OrderTbl.OrdNo = OrdLine.OrdNo
JOIN Product ON OrdLine.ProdNo = Product.ProdNo
GROUP BY OrderTbl.EmpNo;

'''
Q9=  psql.sqldf(txt)
Q9

      EmpNo   Amount
0      None  1432.67
1  E1329594   538.00
2  E8544399  1486.11
3  E8843211  1793.99
4  E9345771  1666.96
5  E9884325   523.67
6  E9954302  1690.97

In [39]:
#10-List the total commission earned by each employee in each month of 2017.
txt='''
SELECT OrderTbl.EmpNo, strftime('%m', OrdDate) AS Month, SUM(Product.ProdPrice * OrdLine.Qty * Employee.EmpCommRate) AS TotalCommission
FROM OrderTbl
JOIN OrdLine ON OrderTbl.OrdNo = OrdLine.OrdNo
JOIN Product ON OrdLine.ProdNo = Product.ProdNo
JOIN Employee ON Employee.EmpNo = OrderTbl.EmpNo
WHERE OrdDate LIKE '2017%'
GROUP BY OrderTbl.EmpNo, strftime('%m', OrdDate);
'''
Q10 =  psql.sqldf(txt)
Q10

      EmpNo Month  TotalCommission
0  E1329594    01          10.7600
1  E8544399    01          12.2532
2  E8544399    02          17.4690
3  E8843211    01          71.7596
4  E9345771    01          66.6784
5  E9884325    01          26.1835
6  E9954302    01           9.4596
7  E9954302    02          24.3598

In [40]:
#11-List the customer first and last name and order number and employee first name and last name
#who handled that order where order is given in February 2017.
#.If order is internet order, include them as well
#Note:If order is internet order, employee first name and last name will be null
txt='''

SELECT Customer.CustFirstName, Customer.CustLastName, OrderTbl.OrdNo, Employee.EmpFirstName, Employee.EmpLastName
FROM Customer JOIN OrderTbl ON Customer.CustNo = OrderTbl.CustNo
LEFT JOIN Employee ON OrderTbl.EmpNo = Employee.EmpNo
WHERE OrderTbl.OrdDate >= '2017-02-01' AND  OrderTbl.OrdDate <= '2017-02-28'
ORDER BY OrderTbl.OrdNo;
'''
Q11=  psql.sqldf(txt)
Q11

  CustFirstName CustLastName     OrdNo EmpFirstName EmpLastName
0          Todd        Hayes  O1241518         None        None
1           Ron     Thompson  O1656777         None        None
2           Ron     Thompson  O7959898          Joe     Jenkins
3         Homer        Wells  O9919699         Mary        Hill

In [43]:
#12-List the total commission earned by each employee. Includenemployee first and last name,
#supervisor last name and first name if any.If employee does not have supervisor, supervisor last name and first name will be null.
txt = '''
SELECT Employee.EmpNo,
       Employee.EmpFirstName,
       Employee.EmpLastName,
       SUM(Product.ProdPrice * OrdLine.Qty * Employee.EmpCommRate) AS 'Commission Earned',
       S.EmpFirstName AS 'Supervisor First Name',
       S.EmpLastName AS 'Supervisor Last Name'
FROM Employee
LEFT JOIN Employee S ON Employee.SupEmpNo = S.EmpNo
JOIN OrderTbl ON Employee.EmpNo = OrderTbl.EmpNo
JOIN OrdLine ON OrderTbl.OrdNo = OrdLine.OrdNo
JOIN Product ON OrdLine.ProdNo = Product.ProdNo
GROUP BY Employee.EmpNo;
'''

Q12 = psql.sqldf(txt)
Q12

,EmpNo,EmpFirstName,EmpLastName,Commission Earned,Supervisor First Name,Supervisor Last Name
0,E1329594,Landi,Santos,10.7600,Amy,Tang
1,E8544399,Joe,Jenkins,29.7222,Amy,Tang
2,E8843211,Amy,Tang,71.7596,Thomas,Johnson
3,E9345771,Colin,White,66.6784,Thomas,Johnson
4,E9884325,Thomas,Johnson,26.1835,None,None
5,E9954302,Mary,Hill,33.8194,Amy,Tang

In [44]:
#13- List product information which is not ordered?
#Note: if here is not such product, nothing other than column name will be displayed.
txt = '''
SELECT Product.*
FROM Product
LEFT JOIN OrdLine ON Product.ProdNo = OrdLine.ProdNo
WHERE OrdLine.ProdNo IS NULL;
'''

Q13 = psql.sqldf(txt)
Q13

Empty DataFrame
Columns: [ProdNo, ProdName, ProdMfg, ProdQOH, ProdPrice, ProdNextShipDate]
Index: []

In [45]:
#14-How many times each product are ordered? What is the total value of orders taken by each product?
#Whatis the total quantity ordered for each product?

txt = '''
SELECT Product.ProdNo,
       COUNT(OrdLine.OrdNo) AS 'Times Ordered',
       SUM(Product.ProdPrice * OrdLine.Qty) AS 'Total Value',
       SUM(OrdLine.Qty) AS 'Total Quantity'
FROM Product
JOIN OrdLine ON Product.ProdNo = OrdLine.ProdNo
GROUP BY Product.ProdNo;
'''

Q14 = psql.sqldf(txt)
Q14

     ProdNo  Times Ordered  Total Value  Total Quantity
0  P0036566              5      2366.00              14
1  P0036577              3       957.00               3
2  P1114590              3      2796.00               4
3  P1412138              6       132.00              11
4  P1445671              9       164.89              11
5  P1556678              7      1089.00              11
6  P3455443              3       266.00               7
7  P4200344              4       799.96               4
8  P6677900              4       205.52               8
9  P9995676              4       356.00               4

In [46]:
#15. How many product are there without ProdNextShipDate.
#What is their average price?
txt = '''
SELECT COUNT(*) AS 'Number of Products',
       AVG(ProdPrice) AS 'Average Price'
FROM Product
WHERE ProdNextShipDate IS NULL;
'''

Q15 = psql.sqldf(txt)
Q15

   Number of Products  Average Price
0                   3          17.56